---

# master playbook

- hosts: all
  roles:
  - { role: common, action: 'install_java' }
  - { role: common, action: 'prepare_hosts' }

- hosts: NameNode
  roles:
  - { role: hadoop-manager, action: 'hadoop_stop_services' }

- hosts: hadoop
  roles:
  - { role: hadoop-manager, action: 'hadoop_provision' }
  - { role: hadoop-manager, action: 'hadoop_namenode_setup_ec2' }
  - { role: hadoop-manager, action: 'hadoop_configuration' }
  - { role: hadoop-manager, action: 'hadoop_add_datanodes' }

- hosts: NameNode
  roles:
#  - { role: hadoop-manager, action: 'hadoop_namenode_setup_non-ec2'}
  - { role: hadoop-manager, action: 'hadoop_format_hdfs' }

