---
- file: path={{ hadoop_path }}/etc/hadoop/slaves state=absent
  sudo: yes

- copy: src=prod-slaves dest={{ hadoop_path }}/etc/hadoop/slaves force=yes
#  when: "stage_prod == 'prod'"
  sudo: yes
 
#- copy: src=stage-slaves dest={{ hadoop_path }}/etc/hadoop/slaves force=yes
#  when: "stage_prod == 'stage'"


