---
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="#Set Hadoop-related environment variables by ansible "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_PREFIX={{ hadoop_path }} "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_HOME={{ hadoop_path }} "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_MAPRED_HOME=${HADOOP_HOME} "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_COMMON_HOME=${HADOOP_HOME} "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_HDFS_HOME=${HADOOP_HOME} "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export YARN_HOME=${HADOOP_HOME} "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="#Native Path by ansible "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_COMMON_LIB_NATIVE_DIR=${HADOOP_PREFIX}/lib/native "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export HADOOP_OPTS="-Djava.library.path=$HADOOP_PREFIX/lib" "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="#Java path by ansible "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export JAVA_HOME='{{ java_path }}' "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="#Add Hadoop bin/ directory to PATH "
- lineinfile: dest={{ hadoop_user_home_dir }}/.bashrc line="export PATH=$PATH:$HADOOP_HOME/bin:$JAVA_PATH/bin:$HADOOP_HOME/sbin "

- shell: source {{ hadoop_user_home_dir }}/.bashrc

- shell: . /etc/profile

- copy: src=hadoop-env.sh dest={{ hadoop_path }}/etc/hadoop/hadoop-env.sh force=yes
  sudo: yes

#- copy: src=stage-yarn-site.xml dest={{ hadoop_path }}/etc/hadoop/yarn-site.xml force=yes
#  sudo: yes
#  when: "stage_prod == 'stage'"

#- copy: src=stage-core-site.xml dest={{ hadoop_path }}/etc/hadoop/core-site.xml force=yes
#  sudo: yes
#  when: "stage_prod == 'stage'"
 
#- copy: src=stage-mapred-site.xml dest={{ hadoop_path }}/etc/hadoop/mapred-site.xml force=yes
#  when: "stage_prod == 'stage'"
#  sudo: yes

- file: path={{ hadoop_path }}/yarn_data/hdfs/namenode state=directory owner={{ sudo_user }} recurse=yes
  sudo: yes

- file: path={{ hadoop_path }}/yarn_data/hdfs/datanode state=directory owner={{ sudo_user }} recurse=yes
  sudo: yes

#- copy: src=stage-hdfs-site.xml dest={{ hadoop_path }}/etc/hadoop/hdfs-site.xml force=yes
#  sudo: yes

- copy: src=prod-yarn-site.xml dest={{ hadoop_path }}/etc/hadoop/yarn-site.xml force=yes
  sudo: yes

- copy: src=prod-core-site.xml dest={{ hadoop_path }}/etc/hadoop/core-site.xml force=yes
  sudo: yes

- copy: src=prod-mapred-site.xml dest={{ hadoop_path }}/etc/hadoop/mapred-site.xml force=yes
  sudo: yes

- copy: src=prod-hdfs-site.xml dest={{ hadoop_path }}/etc/hadoop/hdfs-site.xml force=yes
  sudo: yes

- shell: "sudo chown -R {{ sudo_user }} {{ hadoop_path }}"
