---
- file: path={{ hadoop_path }} state=absent
  sudo: yes

- file: path=/tmp/hadoop* state=absent
  sudo: yes
#  sudo_user: {{ Sudo_User }}

- file: path=/tmp/Jetty* state=absent
  sudo: yes
#  sudo_user: {{ Sudo_User }}
#- user: name=hduser comment="Hadoop user" group=hadoop

- file: path={{ hadoop_parent_path }} state=directory

- name: Copy and unpack hadoop tar file
  unarchive: src={{ hadoop_user_home_dir }}/awa/binaries/hadoop-2.6.0.tar.gz dest={{ hadoop_parent_path }} force=yes owner={{ sudo_user }}
  sudo: yes

- shell: "sudo chown -R {{ sudo_user }} {{ hadoop_path }}"
  


 
