--- 

- include: "hadoop_stop_services.yml"
  when: action == 'hadoop_stop_services'

- include: "hadoop_provision.yml"
  when: action == 'hadoop_provision' 

- include: "hadoop_namenode_setup_ec2.yml"
  when: action == 'hadoop_namenode_setup_ec2'

#- include: "hadoop_namenode_setup_non-ec2.yml"
#  when: action == 'hadoop_namenode_setup_non-ec2'

- include: "hadoop_configuration.yml"
  when: action == 'hadoop_configuration'

- include: "hadoop_add_datanodes.yml"
  when: action == 'hadoop_add_datanodes'

- include: "hadoop_format_hdfs.yml"
  when: action == 'hadoop_format_hdfs' 

- include: "hadoop_start_hdfs.yml"
  when: action == 'hadoop_start_hdfs' 

- include: "hadoop_start_yarn.yml"
  when: action == 'hadoop_start_yarn' 

