#- shell: "hadoop fs -rm -R {{ hdfs_data_input_path }}"
#- shell: "hadoop fs -rm -R {{ hdfs_data_output_path }}"
- shell: "hadoop fs -mkdir /input"
  ignore_errors: true
- copy: src=data dest={{ data_file_absolute_path }} owner=ec2-user force=yes
- shell: "hadoop fs -mkdir {{ hdfs_data_input_path }}"
  ignore_errors: true

- shell: "hadoop fs -rm -R {{ hdfs_data_output_path }}"
  ignore_errors: true

- shell: "hadoop fs -copyFromLocal -f {{ data_file_absolute_path }}/data/ {{ hdfs_data_input_path }}"


