---

- file: path={{ awd }} state=directory

#- name: disable ipv6
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="#disable ipv6"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="net.ipv6.conf.all.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="net.ipv6.conf.default.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="net.ipv6.conf.lo.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="#disable ipv6"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.all.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.default.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.lo.disable_ipv6 = 1"
  sudo: yes

#- name: add hosts to /etc/hosts
#  lineinfile: dest=/etc/hosts state=absent regexp="{{ ansible_eth0.ipv4.address }} {{ etc_hosts_name }} {{ ansible_hostname }}"
#  with_items: groups['all']



