---

- file: path={{ awd }} state=directory

#- name: disable ipv6
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="#disable ipv6"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="net.ipv6.conf.all.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="net.ipv6.conf.default.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf state=absent regexp="net.ipv6.conf.lo.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="#disable ipv6"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.all.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.default.disable_ipv6 = 1"
  sudo: yes
- lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.lo.disable_ipv6 = 1"
  sudo: yes

#- name: add hosts to /etc/hosts
#  lineinfile: dest=/etc/hosts state=absent regexp="{{ ansible_eth0.ipv4.address }} {{ etc_hosts_name }} {{ ansible_hostname }}"
#  with_items: groups['all']

#- lineinfile: dest=/etc/hosts line="192.168.8.154 vm1008.itp.objectfrontier.com vm1008"
#- lineinfile: dest=/etc/hosts line="192.168.8.153 vm1009.itp.objectfrontier.com vm1009"
#- lineinfile: dest=/etc/hosts line="192.168.8.160 vm1010.itp.objectfrontier.com vm1010"
#- lineinfile: dest=/etc/hosts line="172.31.40.39 ec2-54-148-124-229.us-west-2.compute.amazonaws.com ip-172-31-40-39"
#- lineinfile: dest=/etc/hosts line="172-31-25-72 ec2-52-10-66-46.us-west-2.compute.amazonaws.com ip-172-31-25-72"
#- lineinfile: dest=/etc/hosts line="172-31-25-73 ec2-52-11-43-252.us-west-2.compute.amazonaws.com ip-172-31-25-73"
#- lineinfile: dest=/etc/hosts line="172-31-25-71 ec2-52-10-254-60.us-west-2.compute.amazonaws.com ip-172-31-25-71"


